Fix node load alerts for CAPI
giantswarm/prometheus-rules pull request #1188
Opened 2024-05-16 19:14 UTC by QuentinBisson

Before adding a new alerting rule into this repository you should consider creating an SLO rules instead.
SLO helps you both increase the quality of your monitoring and reduce the alert noise.

* How to create a SLO rule: https://github.com/giantswarm/sloth-rules#how-to-create-a-slo
* Documentation: https://intranet.giantswarm.io/docs/monitoring/slo-alerting/

---
Towards: https://github.com/giantswarm/...

This PR fixes some pint warning but also fixes the node load alerts for CAPI as the ip label does not exist in CAPI land because CAPI does not add it to the nodes.

@giantswarm/team-turtles could you check that this is alright? I think the comment above the query makes no sense but I'm not into fixing it myself as I'm not even sure if you want to keep this alert

### Checklist

- [x] Update CHANGELOG.md
- [ ] Add [Unit tests](https://github.com/giantswarm/prometheus-rules/#testing)
- [ ] Follow [Alert structure](https://github.com/giantswarm/prometheus-rules/#how-alerts-are-structured)
- [ ] Consider [creating a dashboard](https://docs.giantswarm.io/getting-started/observability/grafana/custom-dashboards/) ([guidelines](https://intranet.giantswarm.io/docs/product/ux/guidelines/dashboards/)) (if it does not exist already) to help oncallers monitor the status of the issue.
- [ ] Request review from oncall area, as well as team (e.g: `oncall-kaas-cloud` GitHub group).

2024-05-16 20:01 UTC, weseven requested changes
Left a couple of comments, thanks!
Not sure why `without` was used in that way :thinking:

2024-05-16 21:23 UTC, QuentinBisson commented on helm/prometheus-rules/templates/alerting-rules/node.management_cluster.rules.yml
> +          sum(node_load15{cluster_type="management_cluster", app!="vault", role!="bastion"})
Yes we do :)

2024-05-16 21:24 UTC, QuentinBisson commented on helm/prometheus-rules/templates/alerting-rules/node.management_cluster.rules.yml
> +          / count(rate(node_cpu_seconds_total{cluster_type="management_cluster", app!="vault", role!="bastion"}[5m]))
We did not have this before but that's your alert 😅

2024-05-16 21:25 UTC, QuentinBisson commented on helm/prometheus-rules/templates/alerting-rules/node.management_cluster.rules.yml
> +          sum(node_load15{cluster_type="management_cluster", app!="vault", role!="bastion"})
That's configured by prometheus and we have the différence there

2024-05-17 08:16 UTC, weseven approved these changes

2024-05-17 08:23 UTC, merged