Push to openstack app collection
giantswarm/prometheus-rules pull request #217
Opened 2022-01-19 17:25 UTC by tfussell

This PR:

- adds/changes/removes etc

### Checklist

- [ ] Update changelog in CHANGELOG.md.
- [ ] Request review from oncall area, as well as team (e.g: `oncall-kaas-cloud` GitHub group).
- [ ] Alerting rules must have a comment documenting why it needs to exist.

2022-01-19 20:06 UTC, kopiczko approved these changes

2022-01-20 08:24 UTC, QuentinBisson approved these changes

2022-01-20 10:32 UTC, TheoBrigitte requested changes
Ok, but could we not add this `push-to` prefix everywhere please ? I find that it makes things less readable.

2022-01-20 13:45 UTC, tfussell commented
> Ok, but could we not add this `push-to` prefix everywhere please ? I find that it makes things less readable.

@TheoBrigitte I did this because we use this naming convention in basically all of our other CI pipelines and I think the consistency is important. I found it initially confusing when I looked at the file and the job name didn't contain `push-to-`. Maybe something to bring to SIG Releng?

2022-01-22 19:54 UTC, tfussell commented
Closing in favor of https://github.com/giantswarm/prometheus-rules/pull/214

2022-01-22 19:54 UTC, closed without merging