Add CAPZ support
giantswarm/prometheus-rules pull request #541
Opened 2022-12-01 13:55 UTC by QuentinBisson

This PR:

- adds capz support

### Checklist

- [x] Update changelog in CHANGELOG.md.
- [x] Request review from oncall area, as well as team (e.g: `oncall-kaas-cloud` GitHub group).

2022-12-01 14:10 UTC, bavarianbidi requested changes

2022-12-01 14:10 UTC, bavarianbidi commented on helm/prometheus-rules/templates/_helpers.tpl
> +{{- else if eq .Values.managementCluster.provider.kind "capz" -}}
```suggestion
{{- else if eq .Values.managementCluster.provider.kind "capz" -}}
clippy
```

or am i wrong?

2022-12-01 14:24 UTC, QuentinBisson commented on helm/prometheus-rules/templates/_helpers.tpl
> +{{- else if eq .Values.managementCluster.provider.kind "capz" -}}
No you were right :D

2022-12-06 14:41 UTC, bavarianbidi approved these changes

2022-12-06 14:57 UTC, merged