Add team labels
giantswarm/prometheus-rules pull request #653
Opened 2023-02-27 15:56 UTC by QuentinBisson

Towards: https://github.com/giantswarm/giantswarm/issues/18281

This PR adds the team label to prometheus rules so they can be picked up by the change introduced in https://github.com/giantswarm/prometheus-meta-operator/pull/1181

### Checklist

- [x] Update CHANGELOG.md
- [ ] Request review from oncall area, as well as team (e.g: `oncall-kaas-cloud` GitHub group).

2023-02-27 16:08 UTC, QuantumEnigmaa requested changes

2023-02-27 16:08 UTC, QuantumEnigmaa commented on helm/prometheus-rules/templates/_helpers.tpl
> +application.giantswarm.io/team: {{ index .Chart.Annotations "application.giantswarm.io/team" | quote }}
```suggestion
application.giantswarm.io/team: {{ index .Chart.Annotations "application.giantswarm.io/team" | default "atlas" | quote }}
```

2023-02-28 09:01 UTC, QuantumEnigmaa approved these changes

2023-02-28 09:09 UTC, hervenicol approved these changes
Looking good.
I wonder if we can override it per rules-file. I mean, the whole chart belongs to us, but in practice each rules file belongs to a different team, right?

2023-02-28 09:12 UTC, QuentinBisson commented
Yes we should be able to as long as we have the team. But some rules are for multiple teams :(

2023-02-28 09:29 UTC, merged